[config]

[templates.openrgb]
input_path = 'templates/openrgb_dummy'
post_hook = 'openrgb -c {{colors.source_color.default.hex_stripped}}'

[templates.hyprland]
input_path = 'templates/hyprland_colors.conf'
output_path = '~/.config/hypr/colors.conf'
post_hook = 'hyprctl reload'

[templates.quickshell]
input_path = 'templates/quickshell_theme.qml'
output_path = '~/.config/quickshell/Theme.qml'

[templates.wlogout]
input_path = 'templates/all_colors.css'
output_path = '~/.config/wlogout/colors.css'

[templates.rofi]
input_path = 'templates/rofi_theme.rasi'
output_path = '~/.config/rofi/colors.rasi'

[templates.wezterm]
input_path = 'templates/wezterm_theme.toml'
output_path = '~/.config/wezterm/colors/matugen_theme.toml'
post_hook = 'touch ~/.config/wezterm/wezterm.lua'

# [templates.alacritty]
# input_path = 'templates/alacritty_colors.toml'
# output_path = '~/.config/alacritty/colors.toml'

[templates.starship]
input_path = 'templates/starship_template.toml'
output_path = '~/.config/starship.toml'

[templates.eza]
input_path = 'templates/eza_theme.yml'
output_path = '~/.config/eza/theme.yml'

[templates.pywalfox]
input_path = 'templates/pywalfox_colors.json'
output_path = '~/.cache/wal/colors.json'
post_hook = 'pywalfox update'

[templates.vesktop]
input_path = 'templates/vesktop_theme.css'
output_path = '~/.config/vesktop/themes/midnight-discord.css'

[templates.btop]
input_path = 'templates/btop_colors.theme'
output_path = '~/.config/btop/themes/matugen.theme'
post_hook = 'if pidof btop > /dev/null; then pkill -SIGUSR2 btop; fi'

[templates.qt6ct]
input_path = 'templates/qt6ct_colors.conf'
output_path = '~/.config/qt6ct/colors/matugen.conf'
post_hook = 'touch ~/.config/qt6ct/qt6ct.conf'

[templates.nvim]
input_path = 'templates/nvim_colors.lua'
output_path = '~/.config/nvim/lua/matugen.lua'
post_hook = 'pkill -SIGUSR1 nvim'

[templates.spf]
input_path = 'templates/superfile_theme.toml'
output_path = '~/.config/superfile/theme/matugen.toml'

[templates.waypaper]
input_path = 'templates/all_colors.css'
output_path = '~/.config/waypaper/colors.css'

[templates.spicetify]
input_path = 'templates/spicetify_color.ini'
output_path = '~/.config/spicetify/Themes/text/color.ini'
post_hook = '~/.config/matugen/scripts/spicetify_reload.sh'

[templates.vencord]
input_path = 'templates/vencord_midnight.css'
output_path = '~/.config/vesktop/themes/midnight.theme.css'
