[general]
import = ["colors.toml"]

[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 12

[font.normal]
family = "AnonymicePro Nerd Font Mono"

[window]
decorations = "None"
dynamic_padding = true
opacity = 0.9

[cursor]
style = { shape = "Block", blinking = "Never"}

[terminal]
shell = "/usr/bin/fish"
