[colors.primary]
background = '{{colors.background.default.hex}}'
foreground = '{{colors.on_surface.default.hex}}'
 
[colors.search.matches]
foreground = '{{colors.surface_variant.default.hex}}' 
background = '{{colors.tertiary.default.hex}}' 
 
[colors.search.focused_match]
foreground = '{{colors.surface_variant.default.hex}}' 
background = '{{colors.primary.default.hex}}' 
 
[colors.footer_bar]
foreground = '{{colors.surface_variant.default.hex}}' 
background = '{{colors.inverse_surface.default.hex}}' 
 
[colors.hints.start]
foreground = '{{colors.surface_variant.default.hex}}' 
background = '{{colors.secondary.default.hex}}' 
 
[colors.hints.end]
foreground = '{{colors.surface_variant.default.hex}}' 
background = '{{colors.secondary.default.hex}}' 
 
[colors.selection]
text = '{{colors.background.default.hex}}'
background = '{{colors.primary.default.hex}}'
 
[colors.normal]
black = '#191919' 
red = '#D90202'
green = '#7FB11B'
yellow = '#FFD739'
blue = '#3570D7'
magenta = '#BE84FF'
cyan = '#66D9EF'
white = '#F8F8F8'

[colors.bright]
black = '#4D4D4D'
red = '#FF4747'
green = '#A0D04D'
yellow = '#FFEB4D'
blue = '#6A9FF7'
magenta = '#D9A6FF'
cyan = '#80F5FF'
white = '#FFFFFF'

[colors.dim]
black = '#0A0A0A'
red = '#9C0000'
green = '#4E6B11'
yellow = '#B58F17'
blue = '#1C4F9C'
magenta = '#7A4D99'
cyan = '#1E5E6A'
white = '#B0B0B0'
