[colors]
background = "{{colors.background.default.hex}}"
foreground = "{{colors.on_surface.default.hex}}"
cursor_bg = "{{colors.on_surface.default.hex}}"
cursor_border = "{{colors.on_surface.default.hex}}"
cursor_fg = "{{colors.on_surface_variant.default.hex}}"
selection_bg = "{{colors.secondary_fixed_dim.default.hex}}"
selection_fg = "{{colors.on_secondary.default.hex}}"

split = "{{colors.secondary_fixed_dim.default.hex}}"

ansi = [
    "#181818",
    "{{colors.error.default.hex}}",
    "{{colors.primary.default.hex}}",
    "{{colors.inverse_primary.default.hex}}",
    "{{colors.primary.default.hex}}",
    "{{colors.tertiary.default.hex}}",
    "{{colors.secondary.default.hex}}",
    "#BAC2DE"
]

brights = [
    "#585B70",
    "#F38BA8",
    "#A6E3A1",
    "#F9E2AF",
    "#89B4FA",
    "#F5C2E7",
    "#94E2D5",
    "#A6ADC8"
]
